name: Deploy aws-mlops-key
on:
  workflow_dispatch:
    inputs:
      tfvars:
        description: "Path to tfvars (e.g., envs/client-demo.tfvars)"
        required: true
        default: "envs/client-demo.tfvars"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform apply -auto-approve -var-file="${{ github.event.inputs.tfvars }}"
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
